[
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503862,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "qPsgSklCBWk6ebBa/ACGeLoWMY-BzoZgR0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503877,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "qPsgSklCBWk6ebBa/ACGeLoWMY-BzoZgR0"
    },
    {
        "domain": "www.google.com",
        "expirationDate": 1611951998,
        "hostOnly": true,
        "httpOnly": false,
        "name": "UULE",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "a+cm9sZTogMQpwcm9kdWNlcjogMTIKdGltZXN0YW1wOiAxNjExOTMwMzk4NDc3MDAwCmxhdGxuZyB7CiAgbGF0aXR1ZGVfZTc6IDEwODEwMTYzMgogIGxvbmdpdHVkZV9lNzogMTA2NzI4NjUyOAp9CnJhZGl1czogMjY3ODY5MTQwCnByb3ZlbmFuY2U6IDYK"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1611930696.410043,
        "hostOnly": false,
        "httpOnly": true,
        "name": "CONSISTENCY",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKJVzcpzQHOfsLpvLjhRjbWZub5b0c4L6S4EVprVDvMUIf4Q9DwnJk9olTOLNdx5_DNbVXcqp3z6qwedhQ-UhGxWD5Jkd_XMyUN9ECV-Wskfc59JE0iUZlcuBbpev7xw0ZRaFtLxj2ce"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1627741598.403167,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "208=cQ2U6IGP9ZC9mY-X4-x-roxF_V0IsUDYJHQx62snrADeFkZKHW1J44iG6W-7QzEMGeqjowA1wOrzzdlC7Hti1EFZKHTspnZrzgpLydy4p81HwSngtknbBBpQtJFVdrfzkDPVrsT5g-UOdC7nrB5HUIGjb3oW-uJAWRBBB_0RL3JCByod6L1sqbUFxie6zPZyyxHh0bKd4SD0MJYmcQzjiAco93Ko7vg"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503849,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "00kiDTZBv_k7bwrN/A0gS_HjDFqQh6gmoZ"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503779,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "6QdpFlttVjJfL9um-nnUTdKfllU21NFEkeH4Zy5HpaADOTmGELTn-erC6Hjgp-P1bLgq9g."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1614522398.125464,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2021-01-29-14"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1643466402.700851,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AJi4QfGGfPMAKKigk5eb9iQLjZDRI9Pfs6sVp1JAZT86IUrDFti61dzOZVqFWS4yaG3QH55J"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503823,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "AWIrJkaRNQ-3_OnZ8"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1627482398.125507,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "CgQI4JEB"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503745,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "6QdpFlttVjJfL9um-nnUTdKfllU21NFEkeH4Zy5HpaADOTmGaXHMFklJ0xdXn67C66iwKg."
    },
    {
        "domain": ".google.com",
        "expirationDate": 1643466402.700801,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "AJi4QfEx9L6LQa0LQXvw8cvm6gf6NExDf9eF_tV6ITKwj8NgWHgBBHVxdIl1NQzJoAxlWbHgMw"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1675002395.503837,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AhjRdKJv7QA-EFyYb"
    }
]
